name: Wobject
version: '0.0.0'
main: com.tksimeji.wobject.Wobject
api-version: '1.21'
commands:
  wobject:
    description: Command set for Wobject.
    usage: /wobject <subcommand> [args...]
permissions:
  wobject.*:
    default: op
    children:
      wobject.class-list: true
      wobject.break: true
      wobject.new: true
      wobject.wobject-list: true
